# Generated by Django 5.1.7 on 2025-03-25 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_device_linked', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('participation_discount', models.FloatField(default=0.05)),
                ('driving_discount', models.FloatField(default=0.0)),
                ('total_discount', models.FloatField(default=0.05)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('participation_discount', models.FloatField()),
                ('driving_discount', models.FloatField()),
                ('total_discount', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_history', to='bbi_app.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('distance_miles', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('average_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hard_brakes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rapid_accelerations', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('night_driving', models.BooleanField(default=False)),
                ('speed_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('braking_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('acceleration_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bbi_app.driverprofile')),
            ],
        ),
    ]
