# Generated by Django 5.1.7 on 2025-03-25 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_api', '0001_initial'),
        ('bbi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.FloatField()),
                ('is_allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('speed', 'Speed Threshold'), ('geo', 'Geofence Violation'), ('hard_brake', 'Hard Braking'), ('accel', 'Rapid Acceleration')], max_length=20)),
                ('threshold', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbi_app.driverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbi_app.driverprofile')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbi_api.alertrule')),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbi_app.driverprofile')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbi_api.geofence')),
            ],
        ),
    ]
